//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ladder
    {
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> TeamPoint { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Drawn { get; set; }
        public Nullable<int> Lost { get; set; }
    
        public virtual Teams Teams { get; set; }
    }
}
